### ISSUE TITLE
Troubles during PSD/JPG analysing with XML/hexdump presence

### ISSUE THREAD

**Issue by hdsdi3g** [hdsdi3g/MyDMAM#218]
```
2016-12-19 21:32:03,137 ERROR mydmam.metadata ‹WorkerExec:METADATA:WorkerIndexer/job:ea1e44b4›  Can't analyst/render file, analyser class: hd3gtv.mydmam.transcode.images.ImageMagickAnalyser@2a10fcfb, analy ser name: ImageMagick Analyser, physical_source: /mnt/na/ME/HA/BI/fr/Li/Ge/NT.psd
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 128 column 8 path $.image.clipping path.<?xml
        at com.google.gson.internal.Streams.parse(Streams.java:60)
        at com.google.gson.JsonParser.parse(JsonParser.java:84)
        at com.google.gson.JsonParser.parse(JsonParser.java:59)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at hd3gtv.mydmam.transcode.images.ImageMagickAnalyser.processFull(ImageMagickAnalyser.java:130)
        at hd3gtv.mydmam.metadata.MetadataIndexingOperation.doIndexing(MetadataIndexingOperation.java:173)
        at hd3gtv.mydmam.metadata.MetadataStorageIndexer.processFoundedElement(MetadataStorageIndexer.java:276)
        at hd3gtv.mydmam.metadata.MetadataStorageIndexer.process(MetadataStorageIndexer.java:114)
        at hd3gtv.mydmam.metadata.WorkerIndexer.workerProcessJob(WorkerIndexer.java:96)
        at hd3gtv.mydmam.manager.WorkerNG$Executor.run(WorkerNG.java:181)
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 128 column 8 path $.image.clipping path.<?xml
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:720)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
        at com.google.gson.internal.Streams.parse(Streams.java:48)
        ... 9 more

```
And

```
2016-12-19 22:23:10,293 ERROR mydmam.metadata ‹WorkerExec:METADATA:WorkerIndexer/job:ea1e44b4›  Can't analyst/render file, analyser class: hd3gtv.mydmam.transcode.images.ImageMagickAnalyser@2a10fcfb, analy ser name: ImageMagick Analyser, physical_source: /mnt/na/ME/HA/Ha/DI/PR/DI/(Me/PS/CA/CA.jpg
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 192 column 82 path $.image.profiles.iptc.0x00000014: ff4fffff ffffff44 07263656 ffff3bff 4175ff60  - -O-----D-&6V--;-Au-
        at com.google.gson.internal.Streams.parse(Streams.java:60)
        at com.google.gson.JsonParser.parse(JsonParser.java:84)
        at com.google.gson.JsonParser.parse(JsonParser.java:59)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at hd3gtv.mydmam.transcode.images.ImageMagickAnalyser.processFull(ImageMagickAnalyser.java:130)
        at hd3gtv.mydmam.metadata.MetadataIndexingOperation.doIndexing(MetadataIndexingOperation.java:173)
        at hd3gtv.mydmam.metadata.MetadataStorageIndexer.processFoundedElement(MetadataStorageIndexer.java:276)
        at hd3gtv.mydmam.metadata.MetadataStorageIndexer.process(MetadataStorageIndexer.java:114)
        at hd3gtv.mydmam.metadata.WorkerIndexer.workerProcessJob(WorkerIndexer.java:96)
        at hd3gtv.mydmam.manager.WorkerNG$Executor.run(WorkerNG.java:181)
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 192 column 82 path $.image.profiles.iptc.0x00000014: ff4fffff ffffff44 07263656 ffff3bff 4175ff60  --O-----D-&6V--;-Au-
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:720)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
        at com.google.gson.internal.Streams.parse(Streams.java:48)
        ... 9 more
```

**Comment by hdsdi3g** [comment]
How to parse:

```
      "xap:ModifyDate": "2007-02-27T05:18:59-05:00",
      "xapMM:DocumentID": "adobe:docid:photoshop:db757559-7804-11d7-9067-aed3aec408cb",
      "xapMM:InstanceID": "uuid:F8CAAA58B4C7DB11A6C88751B679D1A9"
    },
    "clipping path": {
<?xml version="1.0" encoding="iso-8859-1"?>
<svg xmlns="http://www.w3.org/2000/svg" width="720" height="480">
<g>
<path fill-rule="evenodd" style="fill:#00000000;stroke:#00000000;stroke-width:0;stroke-antialiasing:false" d="
M 85.4413 311.688
C 85.4413 311.688 161.111 323.192 177.699 307.572
C 194.287 291.951 181.505 238.741 177.396 227.147
C 168.725 202.682 117.426 199.999 72.7525 225.447
C 65.4334 229.616 68.0637 303.168 85.4413 311.688 Z
M 38.4413 19.0983
C 38.4413 19.0983 111.111 4.89804 127.699 20.5184
C 144.287 36.1387 158.505 190.922 151.396 198.022
C 144.287 205.122 36.0716 202.992 29.7525 191.632
C 23.4334 180.272 21.0637 27.6185 38.4413 19.0983 Z
M 204.441 277.531
C 204.441 277.531 280.111 289.035 296.699 273.414
C 313.287 257.794 304.505 131.775 300.396 120.18
C 291.725 95.7152 222.405 77.7571 198.752 120.278
C 192.433 131.639 187.064 269.011 204.441 277.531 Z
"/>
</g>
</svg>

    },
    "profiles": {
      "8bim": {
        "length": "28714"
      },
      "exif": {

```
And 

```
        "Reference Number[2,50]": "",
        "unknown[2,118]": "",
        "unknown[2,130]": "",
        "unknown[2,131]": "",
        "unknown[2,135]": "",
        "unknown[2,231]": "11/10/2016 15:00:35  Text Saved by Orphea Studio (c)1997-2014 Algoba Systems.",
        "Original Transmission Reference[107,103]": "0x00000000: ff2f6b7e ffffff4c ffff0811 27ffffff 520631ff  |-/k~---L----'---R-1",
"0x00000014: ff4fffff ffffff44 07263656 ffff3bff 4175ff60  --O-----D-&6V--;-Au-",
"0x00000028: 20ff7bff ffff7542 43ff3e08 65ff6364 1970ffff  ` -{---uBC->-e-cd-p-",
"0x0000003c: ffffffff ff0a0dff 1f6bffff ff4affff 6d73ffff  ----------k---J--ms-",
"0x00000050: ffffffff ff3f35ff ff55ffff ffffff36 ffffffff  ------?5--U-----6---",
"0x00000064: 07ff5bff ffffff07 ffffff01 ff3f44ff 092851ff  ---[----------?D--(Q",
"0x00000078: ff675d75 ffffff0e ff2c67ff 31ffffff ffffffff  --g]u-----,g-1------",
"0x0000008c: ffffffff 227b6856 460677ff 3347ffff ffff5eff  -----"{hVF-w-3",
"0x000000a0: ffffffff 5effff66 06ffffff 00                 G----^-",
        "length": "7456"
      }
    },
    "artifacts": {
      "filename": "C_O_05.jpg"
    },
    "tainted": "False",
    "filesize": "149KB",
    "numberPixels": "502K",
    "pixelsPerSecond": "50.2MB",
    "userTime": "0.010u",

```
