### ISSUE TITLE
Troubles if an analyzing is stopped and restarted

### ISSUE THREAD

**Issue by hdsdi3g** [hdsdi3g/MyDMAM#220]
A ES entry maybe stay in bad state:

```
Send by: WorkerExec:METADATA:WorkerIndexer/job:839d2b60 (32) from hd3gtv.mydmam.manager.AppManager$ServiceException.onError(AppManager.java:257)

By java.lang.NullPointerException: null
    at hd3gtv.mydmam.metadata.container.ContainerEntry.deserialize(ContainerEntry.java:72)
    at hd3gtv.mydmam.metadata.container.ContainerEntry.deserialize(ContainerEntry.java:1)
    at hd3gtv.mydmam.metadata.container.SelfSerialiserBridge$Deserializer.deserialize(SelfSerialiserBridge.java:65)
    at hd3gtv.mydmam.metadata.container.SelfSerialiserBridge$Deserializer.deserialize(SelfSerialiserBridge.java:1)
    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
    at com.google.gson.Gson.fromJson(Gson.java:879)
    at com.google.gson.Gson.fromJson(Gson.java:844)
    at com.google.gson.Gson.fromJson(Gson.java:793)
    at com.google.gson.Gson.fromJson(Gson.java:765)
    at hd3gtv.mydmam.metadata.container.ContainerOperations$HitReader.onFoundHit(ContainerOperations.java:334)
    at hd3gtv.mydmam.db.ElastisearchCrawlerReader.allReader(ElastisearchCrawlerReader.java:236)
    at hd3gtv.mydmam.db.ElastisearchCrawlerReader.allReader(ElastisearchCrawlerReader.java:144)
    at hd3gtv.mydmam.metadata.container.ContainerOperations.searchInMetadataBase(ContainerOperations.java:371)
    at hd3gtv.mydmam.metadata.container.ContainerOperations.searchInMetadataBase(ContainerOperations.java:291)
    at hd3gtv.mydmam.metadata.container.ContainerOperations.getByPathIndexId(ContainerOperations.java:267)
    at hd3gtv.mydmam.metadata.MetadataStorageIndexer.processFoundedElement(MetadataStorageIndexer.java:156)
    at hd3gtv.mydmam.metadata.MetadataStorageIndexer.process(MetadataStorageIndexer.java:114)
    at hd3gtv.mydmam.metadata.WorkerIndexer.workerProcessJob(WorkerIndexer.java:96)
    at hd3gtv.mydmam.manager.WorkerNG$Executor.run(WorkerNG.java:181)


```

**Comment by hdsdi3g** [comment]
BBCBmx Analyser was the original cause, corrected in #226
